### ISSUE TITLE
Typo in Exchange Rate

### ISSUE THREAD

**Issue by prabh-62** [bhambraj/currency_convertor#3]
<img width="747" alt="exchange_rate_typo" src="https://user-images.githubusercontent.com/13006107/99479270-d6d7e780-2923-11eb-9ddb-02febe7fb854.png">

There is a typo in a exchange rate

**Comment by bhambraj** [comment]
@prabh-62 Thanks for opening this issue. 
Updated here: https://github.com/bhambraj/currency_convertor/commit/43ee3fa43265577e6a7e51fb47975c3938423b81
